const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const rootDir = path.resolve(__dirname, "..");
const appSource = fs.readFileSync(path.join(rootDir, "app.js"), "utf8");
const htmlSource = fs.readFileSync(path.join(rootDir, "index.html"), "utf8");
const stylesSource = fs.readFileSync(path.join(rootDir, "styles.css"), "utf8");
const docSource = fs.readFileSync(path.join(rootDir, "docs/track-feature-optimization-v1.15.md"), "utf8");

assert.match(htmlSource, /Business Jet Radar 1\.18/, "1.18 page title is active");
assert.match(htmlSource, /1\.18-release/, "1.18 cache-busting version is active");
assert.doesNotMatch(htmlSource, /trackQuality|trackActualSegmentCount|trackEstimatedSegmentCount|trackPlannedRouteState|trackRouteColorMode/, "track quality module and its subfields are removed");
assert.match(htmlSource, /id="trackCurrentAltitude"/, "track tab shows current altitude");
assert.match(htmlSource, /id="trackCurrentSpeed"/, "track tab shows current ground speed");
assert.match(htmlSource, /id="trackChartStartTime"/, "track tab shows chart origin timestamp");
assert.match(htmlSource, /id="trackChartEndTime"/, "track tab shows chart current timestamp");
assert.match(htmlSource, /data-chart-unit="imperial"[^>]*>FT \/ KT<\/button>/, "track chart has an imperial unit toggle");
assert.match(htmlSource, /data-chart-unit="metric"[^>]*>M \/ KMH<\/button>/, "track chart has a metric unit toggle");
assert.doesNotMatch(htmlSource, /id="trackHoverTooltip"/, "track hover diagnostic tooltip container is removed");

assert.match(appSource, /version:\s*"1\.15"/, "track standard exports 1.15 version");
assert.doesNotMatch(appSource, /function\s+selectedTrackQualitySummary\(|function\s+renderTrackQualityPanel\(|trackQualitySummary\(/, "track quality evaluation is not implemented or exported");
assert.doesNotMatch(appSource, /function\s+trackSegmentDiagnostic\(/, "track segment diagnostics popup helper is removed");
assert.doesNotMatch(appSource, /function\s+plannedRouteDiagnostic\(/, "planned route diagnostics popup helper is removed");
assert.doesNotMatch(appSource, /function\s+trackTooltipElement\(|function\s+moveTrackTooltip\(|function\s+renderTrackTooltipContent\(|function\s+showTrackHoverTooltip\(|function\s+hideTrackHoverTooltip\(|function\s+handleTrackSegmentHover\(|function\s+handleTrackSegmentMove\(|function\s+handleTrackSegmentOut\(|function\s+handleTrackSegmentClick\(/, "track tooltip interaction helpers are removed");
assert.match(appSource, /function\s+attachSpeedAltitudeChartHover\(/, "speed and altitude chart hover interaction is implemented");
assert.match(appSource, /function\s+chartTimeParts\(/, "speed-altitude chart has UTC and local time formatter");
assert.match(appSource, /function\s+completeSpeedAltitudeChartPoints\(/, "speed-altitude chart completes missing historical/current points");
assert.match(appSource, /function\s+formatChartAltitude\(value,\s*unit\s*=\s*chartUnitMode\(\)\)/, "speed-altitude chart has unit-aware altitude formatting");
assert.match(appSource, /function\s+formatChartSpeed\(value,\s*unit\s*=\s*chartUnitMode\(\)\)/, "speed-altitude chart has unit-aware speed formatting");
assert.match(appSource, /function\s+setSpeedAltitudeUnit\(unit\)/, "speed-altitude chart supports unit switching");
assert.match(appSource, /state\.speedAltitudeUnit\s*=\s*unit;[\s\S]*renderSpeedAltitudeChart\(jet\);/, "unit switching rerenders the selected chart");
assert.match(appSource, /const\s+SPEED_ALTITUDE_CHART_MAX_POINTS\s*=\s*320;/, "speed-altitude chart has a bounded display point budget");
assert.match(appSource, /function\s+sampleSpeedAltitudeChartPoints\(points,\s*maxPoints\s*=\s*SPEED_ALTITUDE_CHART_MAX_POINTS\)/, "speed-altitude chart samples across the whole flight instead of truncating history");
assert.match(appSource, /sampled\.set\(0,\s*sorted\[0\]\);[\s\S]*sampled\.set\(lastIndex,\s*sorted\[lastIndex\]\);/, "speed-altitude chart sampling always keeps the first and latest points");
assert.doesNotMatch(appSource, /completeSpeedAltitudeChartPoints\(jet,\s*startTime,\s*endTime\)\.slice\(-320\)/, "speed-altitude chart no longer drops early metric points");
assert.match(appSource, /function\s+speedAltitudeChartDiagnostics\(/, "speed-altitude chart exposes data coverage diagnostics");
assert.match(appSource, /sourceAltitudePoints:[\s\S]*sourceSpeedPoints:[\s\S]*renderSampling:/, "speed-altitude diagnostics report source metric coverage and render sampling");
assert.match(appSource, /speedAltitudeChartDiagnostics\(jet\)\s*{[\s\S]*return\s+speedAltitudeChartDiagnostics\(jet\);/, "track standard exports speed-altitude diagnostics");
assert.match(appSource, /localAxis:\s*`\$\{localShort\}\s+\$\{localZoneLabel\}`/, "chart axis uses compact local time labels");
assert.match(appSource, /utcAxis:\s*`\$\{utcShort\}Z`/, "chart axis uses compact UTC Z labels");
assert.match(appSource, /combined:\s*`\$\{local\}\s+\$\{localZoneLabel\}\s+·\s+\$\{utc\.replace/, "chart readouts show local time first and UTC second");
assert.match(appSource, /const\s+departedAt\s*=\s*resolvedRouteTimes\.actualDeparture\.epochMs;/, "speed-altitude chart origin uses actual departure time");
assert.match(appSource, /const\s+currentTime\s*=\s*selectPanelNowEpoch\(/, "speed-altitude chart end uses the current/server time");
assert.match(appSource, /speedAltitudeCurrentPoint\(jet,\s*endTime\)/, "speed-altitude chart appends the current aircraft point");
assert.match(appSource, /chartAxisTimeSvg\(pad\.left[\s\S]*chartAxisTimeSvg\(pad\.left \+ plotWidth \* 0\.5[\s\S]*chartAxisTimeSvg\(width - pad\.right/, "chart axis renders start, middle, and end time coordinates");
assert.match(appSource, /data-chart-hover-local-time/, "chart hover card renders converted local time");
assert.match(appSource, /timeText\.textContent\s*=\s*`\$\{timeParts\.local\}\s+\$\{timeParts\.localZone\}`/, "chart hover primary time is local");
assert.match(appSource, /localTimeText\.textContent\s*=\s*`UTC\s+\$\{timeParts\.utc\.replace/, "chart hover secondary time is UTC");
assert.match(appSource, /setText\("trackChartStartTime",\s*startTime \? chartAxisTimeLabel\(startTime,\s*resolvedRouteTimes\)/, "track start readout includes UTC and local time");
assert.match(appSource, /setText\("trackChartEndTime",\s*chartAxisTimeLabel\(endTime,\s*resolvedRouteTimes\)\)/, "track end readout includes UTC and local time");
assert.match(appSource, /setText\("trackCurrentAltitude",\s*formatChartAltitude\(currentAltitude,\s*chartUnit\)\);/, "current altitude follows chart unit mode");
assert.match(appSource, /setText\("trackCurrentSpeed",\s*formatChartSpeed\(currentSpeed,\s*chartUnit\)\);/, "current ground speed follows chart unit mode");
assert.match(appSource, /haloEnabled:\s*false/, "selected track halo/shadow rendering stays disabled");
assert.match(appSource, /record\.hits\s*=\s*new Map\(\)/, "renderers maintain transparent hit-layer maps");
assert.doesNotMatch(appSource, /strokeOpacity:\s*0\.01/, "track hit layers do not draw faint visible shadows");
assert.doesNotMatch(appSource, /\.on\("mouseover",\s*\(event\)\s*=>\s*(?:handleTrackSegmentHover|showTrackHoverTooltip)/, "Leaflet track hover no longer opens route tooltips");
assert.doesNotMatch(appSource, /\.addListener\("mouseover",\s*\(event\)\s*=>\s*(?:handleTrackSegmentHover|showTrackHoverTooltip)/, "Google track hover no longer opens route tooltips");
assert.doesNotMatch(appSource, /\.(?:on|addListener)\("mousemove",\s*handleTrackSegmentMove\)/, "route hover move handlers are removed");
assert.doesNotMatch(appSource, /\.(?:on|addListener)\("mouseout",\s*handleTrackSegmentOut\)/, "route hover out handlers are removed");
assert.doesNotMatch(appSource, /handleTrackSegmentClick\(hit\._bizjetSegment,\s*event\)/, "route click diagnostics are removed");
assert.doesNotMatch(appSource, /showTrackHoverTooltip\(plannedRouteDiagnostic\(\),\s*event,\s*{\s*pinned:\s*true\s*}\)/, "planned route click diagnostics are removed");

assert.doesNotMatch(stylesSource, /\.track-hover-tooltip\s*{/, "track hover tooltip styles are removed");
assert.doesNotMatch(stylesSource, /track-quality-grade|track-quality-section|track-quality-summary|track-quality-grid/, "track quality styles are removed");
assert.match(stylesSource, /\.selected-panel-v114\s+\.chart-hit-zone\s*{[\s\S]*?cursor:\s*crosshair;/, "speed-altitude chart has a hover hit zone");
assert.match(stylesSource, /\.selected-panel-v114\s+\.chart-hover-card\s+rect\s*{/, "speed-altitude chart hover card is styled");
assert.match(stylesSource, /\.chart-unit-toggle\s*{[\s\S]*?grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/, "speed-altitude chart unit toggle is styled as a segmented control");
assert.match(stylesSource, /\.chart-unit-toggle\s+button\.active\s*{[\s\S]*?background:\s*var\(--yellow\);/, "active speed-altitude unit has selected styling");
assert.match(stylesSource, /\.chart-axis-mid\s*{[\s\S]*?text-anchor:\s*middle;/, "middle chart time coordinate is centered");
assert.match(stylesSource, /\.chart-axis-utc\s*{[\s\S]*?fill:\s*rgba\(255,\s*255,\s*255,\s*0\.46\)/, "UTC axis label is visually secondary");
assert.match(docSource, /取消航迹质量评估/, "1.15 document records removal of quality evaluation");
assert.match(docSource, /实际起飞时刻到当前时刻/, "1.15 document records the speed-altitude chart time axis");

console.log("track feature optimization: ok");
